spring:
  application:
    name: merge-notification-server

  cloud:
    function:
      definition: consumeNotification
    stream:
      bindings:
        consumeNotification-in-0:
          destination: merge
